# Generated by Django 5.2.4 on 2025-08-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
