# Generated by Django 5.2.4 on 2025-08-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_yourmodel_remove_resource_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='integer_field',
        ),
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resources',
                to='api.document',
                null=True,  # Temporary allowance for null
                blank=True  # Allow blank in forms/admin
            ),
        ),
        # Add data migration operation to handle existing records
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('api', 'Resource')
                .objects
                .filter(document__isnull=True)
                .update(document=(
                    apps.get_model('api', 'Document')
                    .objects
                    .first() or
                    apps.get_model('api', 'Document')
                    .objects
                    .create(
                        name='Default Document',
                        file='pdfs/default.pdf'
                    )
                ))
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        # Now make the field non-nullable
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resources',
                to='api.document',
                null=False,
                blank=False
            ),
        ),
    ]