# Generated by Django 5.2.4 on 2025-08-03 18:36

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_resource_integer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='branch',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document'),
        ),
    ]
